apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r6v1gdrf4-nodejs
  janus-idp.io/tekton: r6v1gdrf4-nodejs
  backstage.io/kubernetes-id: r6v1gdrf4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r6v1gdrf4-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
